### ISSUE TITLE
Multiple monitors support/help?

### ISSUE THREAD

**Issue by vector-vulture** [jamienicol/gnome-shell-extension-always-zoom-workspaces#10]
Hi. running ubuntu 18.04 here. Was just wondering if you can tell me how to get zoomed in workspace thumbnails reliably on my secondary monitor? if you can point me in the right direction it would be awesome since this is not well documented.

I would like both my monitors to show a zoomed workspace overview at all times. Right now, i'm using the multiple monitors add-on exention and it gives me the row of thumbnails, but not zoomed in on my secondary. your extention has fixed my primary.

This is also the only extension I found that does this, and I don't even understand why this is like this in general. thats why im asking you for help. I am pretty sure that last week or so when I just installed, they were already zoomed in like that. but then suddenly they started being kinda halfway on the screen and only zoom once you hover them.

I noticed I had the exact same thing at my work, where I have the same OS version, same extentions (almost) and same shell themes. So maybe after all this is by design, but then how do I make it work for both my displays?  I managed to fix it at work by changing the main display from as 21:9 ultrawide to my 24" dell monitor, and then miraculously both workspace overviews were zoomed again. 

Any idea how I can go about fixing this for both of my screens or possibly even a third? thanks

**Comment by jamienicol** [comment]
Hi! this isn't a deliberate choice. I'm afraid I just don't use the extension to add the workspaces view to the second monitor, I didn't even know it existed. could you please share the link to it with me?

I can see if I can add support for it. unfortunately, however, I'm working from home at the moment due to the current circumstances, and I don't have a second monitor at home. so I can't promise a quick fix.

**Comment by vector-vulture** [comment]
I super appreciate the quick response, so thanks for that.
extension in question that I've been using: https://extensions.gnome.org/extension/921/multi-monitors-add-on/

But, this behaviour of the overview showing just a half of the workspace thumbnails, happens with just 1 monitor too, right? Isn't that the reason that your extension exist, to eliminate this effect on at least the primary monitor? 

my question is, is that intended behaviour of ubuntu/gnome to hide them like that in the overview? because I can't find a setting or tweak that changes it except for your (awesome) extension.

I don't expect a quick fix at all, that you're even looking into it is great. 
I hope you can figure out how it works so I can have this extension active on all displays, even just a tweak for the terminal will do. t I obviously don't expect anything from you but support would probably be cool, I can't imagine that I'm the only person who likes to have the overview like that.

especially because sometimes they do appear how I want them, but then I restart my PC or logout and it shifts back halfway again on my secondary. I haven't noticed my primary shifting back at all since your extension, so it would be much desired to me.
Side note: putting active windows in the workspaces does not zoom them in either, it stays the same until I do *something* that puts them back.

Kind regards, DBC

EDIT:
Some system info if you need it
uname -a:
Linux $HOSTNAME$ 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
gnome-shell --version:
GNOME Shell 3.28.4
Both your extension and the multiple monitor add on extension  were downloaded from the gnome extensions page in Firefox. Hope this is enough info.

**Comment by vector-vulture** [comment]
Issue is gnome desktop related and not related to this extension. issue will be closed
