### ISSUE TITLE
Still outdated according to Gnome

### ISSUE THREAD

**Issue by j0hannes** [jamienicol/gnome-shell-extension-always-zoom-workspaces#2]
just a hint

**Comment by jamienicol** [comment]
It shouldn't be. What gnome-shell version and distro are you using?

**Comment by j0hannes** [comment]
3.16 and Arch

**Comment by jamienicol** [comment]
Sorry I don't know what to suggest. I'm also on Arch and it works fine for me.

**Comment by j0hannes** [comment]
The extension page seems to be the problem, updating via the extension tool did work.
