### ISSUE TITLE
Upgrade to Gnome Shell 3.36

### ISSUE THREAD

**Issue by galen1423** [jamienicol/gnome-shell-extension-always-zoom-workspaces#8]
Hi,

Thank you for this extension.

Can you consider to upgrade your code with Gnome Shell 3.36 ? Thx.

**Comment by jamienicol** [comment]
Do you know what has changed that makes it not work in 3.36?

**Comment by galen1423** [comment]
I don't known what is change compared other G.S version but i have this error with G.S 3.36 (in effect 3.35.91):
`TypeError: Main.overview._controls is undefined`

**Comment by ai** [comment]
@jamienicol here is the full error stack trace:

```
JS ERROR: Extension alwayszoomworkspaces@jamie.thenicols.net: TypeError: Main.overview._controls is undefined
init@/home/ai/.local/share/gnome-shell/extensions/alwayszoomworkspaces@jamie.thenicols.net/extension.js:24:5
_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:382:50
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:308:27
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:204:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:97:13
```

**Comment by ai** [comment]
@jamienicol seems like you need to replace `Main.overview._controls` to:

```js
let controls = Main.overview._controls
if (!controls) {
  controls = Main.overview._overview._controls
}
```

**Comment by jamienicol** [comment]
@ai Thanks for looking in to it! I've been struggling to find the time!

Have you tested that works? Want to make a pull request? Then I'll merge and publish, if I can remember how :laughing:

**Comment by ai** [comment]
@jamienicol sure https://github.com/jamienicol/gnome-shell-extension-always-zoom-workspaces/pull/9

**Comment by galen1423** [comment]
@ai  

Thanx for your code. This extension now work as expected. :+1:

**Comment by ai** [comment]
@galen1423 great. Let’s wait for release.

**Comment by jamienicol** [comment]
Thanks again @ai! And thank you for testing @galen1423. I have uploaded the new version to extensions.gnome.org, hopefully should be released soon!
